database:
        host: localhost
        port: 5432
        user: postgres
        password: postgres
        database: matchmove_db
        pgDebug:
            verbose: true
            logLevel: INFO
port: 
        port: 8080